### ISSUE TITLE
[인프라] 스프링 시큐리티 설정 및 패키지 구조 설정

### ISSUE THREAD

**Issue by awesomeo184** [prgrms-web-devcourse/Team_Price_Offer_BE#1]
스프링 시큐리티 기본 설정 및 저희가 사용하기로 했던 패키지 구조가 필요합니다.

**Comment by hun-ca** [comment]
![image](https://user-images.githubusercontent.com/55920132/143771658-8c0952cb-75ca-4f68-abcb-e04c86fc47e6.png)

이대로 갈까요?

**Comment by awesomeo184** [comment]
네 일단 예시로 보여주신 레포지토리 맞춰서 만들어서 풀리퀘 보냈습니다
